### ISSUE TITLE
can't access the layers set in template.yaml

### ISSUE THREAD

**Issue by chinapanpan** [aws-samples/sample-serverless-mcp-servers#2]
```
AWSTemplateFormatVersion: '2010-09-09'
Description: MCP deployment on API Gateway and Lambda
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Layers:
      - arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:55
      - arn:aws:lambda:us-east-1:753240598075:layer:LambdaAdapterLayerX86:25
      - !Ref dependencies
```

in template.yaml， there are two layers from other aws account. when "make apigw", a access denied error was reported.
